<?php

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_page_attachments().
 */
function geo_tracking_limit_page_attachments(array &$build) {
  $build['#cache']['contexts'][] = 'ip';

  $build['#attached']['library'][] = 'geo_tracking_limit/datalayer';
  $build['#attached']['drupalSettings']['geo_tracking_limit']['check'] = true;
}