<?php

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_page_attachments().
 */
function iq_geo_tracking_page_attachments(array &$build) {
  $build['#cache']['contexts'][] = 'ip';

  $build['#attached']['library'][] = 'iq_geo_tracking/datalayer';
  $build['#attached']['drupalSettings']['iq_geo_tracking']['check'] = true;
}